CREATE TABLE operation (
    approx_cost float(53) not null,
    distance_end float(53) not null,
    distance_start float(53) not null,
    time integer not null,
    year_end integer not null,
    year_start integer not null,
    id bigint generated by default as identity,
    brand varchar(255) not null,
    description varchar(255),
    engine varchar(255) not null,
    model varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

CREATE INDEX idx_operation_model ON operation(model);
CREATE INDEX idx_operation_brand ON operation(brand);
CREATE INDEX idx_operation_engine ON operation(engine);

CREATE TABLE vehicle (
    make_year integer,
    id bigint generated by default as identity,
    brand varchar(255),
    engine varchar(255),
    model varchar(255),
    primary key (id)
);

CREATE INDEX idx_vehicle_model ON vehicle(model);
CREATE INDEX idx_vehicle_brand ON vehicle(brand);
CREATE INDEX idx_vehicle_engine ON vehicle(engine);