create table operation (approx_cost float(53) not null,
    distance_end float(53) not null,
    distance_start float(53) not null,
    time integer not null,
    year_end integer not null,
    year_start integer not null,
    id bigint generated by default as identity,
    brand varchar(255) not null,
    description varchar(255),
    engine varchar(255) not null,
    model varchar(255) not null,
    name varchar(255) not null,
    primary key (id),
    INDEX (engine),
    INDEX (brand),
    INDEX (engine)
);

create table vehicle (make_year integer,
    id bigint generated by default as identity,
    brand varchar(255),
    engine varchar(255),
    model varchar(255),
    primary key (id),
    INDEX (engine),
    INDEX (brand),
    INDEX (engine)
);